### ISSUE TITLE
crash on terminal window resize

### ISSUE THREAD

**Issue by benkohler** [l4rzy/ncman#3]
If I resize my terminal window a few times while ncman is running, it will eventually crash with

$ ncman
corrupted size vs. prev_size
Aborted (core dumped)
$

I will try to debug this in a bit more detail

**Comment by l4rzy** [comment]
I'm trying to reproduce that (no luck tho), I'm not really sure whether that bug was in the original code or was introduced by my new commits, could you give me the backtrace, or the coredump file?
Anyway, the UI is too old and needs to be rewritten soon.

**Comment by benkohler** [comment]
Ok I see what's going on here.  On my distro, ncurses & ncursesw (wide, unicode support) are 2 separate libs.  The autotools build supported this setup.  But meson.build only asks for ncurses, so it gets one without wide support on my system.

The result is bad unicode char handling (I see lots of corrupt characters in the menu) and the crash I mentioned before.

**Comment by l4rzy** [comment]
Too bad I was not careful enough migrating it to meson build system. 
There is a very good meson.build example here to follow
https://github.com/MusicPlayerDaemon/ncmpc/blob/master/meson.build
I'll check it. Thanks for reporting it to me!

**Comment by benkohler** [comment]
This has been working fine since 409a91945a6581f9a305bc662b28b71c46623127 , thanks!
